name: Build and Publish Docker Image to Dockerhub - Pranav

on:
  push: #action
    branches: [main]  # branch to be triggered on

env:
  DOCKER_HUB_REPO: pranavponugoti16/docker-test

jobs:
  build_push:  #job title
    name: Build and push image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome - Build and Push"

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Use docker/metadata-action
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_HUB_REPO }}
          tags: |
            latest
            ${{ github.ref }}
      
      - name: Build and push to Pranav's Dockerhub
        uses: docker/build-push-action@v4
        with:
          context: . #Location of dockerfile
          file: ./Dockerfile #Name of dockerfile
          push: true #Push to repo
          tags: | 
            ${{ env.DOCKER_HUB_REPO }}:latest
            ${{ steps.metadata.outputs.tags }}
      - run: echo "end of workflow"
